apiVersion: 1

datasources:
   - name: mattermost
     type: prometheus
     access: proxy
     url: http://prometheus:9090
     password:
     user:
     database:
     isDefault: true
     jsonData:
        tlsAuth: false
        tlsAuthWithCACert: false
        httpMethod: "POST"
     version: 1
     editable: true
   - name: loki
     type: loki
     access: proxy
     url: http://loki:3100
     password:
     user:
     database:
     isDefault: false
     jsonData:
        tlsAuth: false
        tlsAuthWithCACert: false
        httpMethod: "POST"
     version: 1
     editable: true
